# Generated by Django 5.2.6 on 2025-09-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=10)),
                ('hodometro', models.FloatField()),
                ('tanqueComb', models.FloatField()),
                ('placa', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='abastecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros', models.FloatField(max_length=20)),
                ('loc_posto', models.CharField(blank=True, max_length=100, null=True)),
                ('data_abastecimento', models.DateField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.veiculo')),
            ],
        ),
    ]
