# Generated by Django 5.2.6 on 2025-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='tanqueComb',
            new_name='tanque_comb',
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='litros',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(max_length=11),
        ),
    ]
