# Generated by Django 5.2.6 on 2025-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_tanquecomb_veiculo_tanque_comb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='placa',
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV')], default='gasolina', max_length=20),
        ),
    ]
