# Generated by Django 5.2.6 on 2025-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_veiculo_placa_alter_abastecer_combustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
