# Generated by Django 5.2.6 on 2025-09-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_veiculo_ano_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecer',
            name='tanque_cheio',
            field=models.BooleanField(default=False),
        ),
    ]
