# Generated by Django 5.2.6 on 2025-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_abastecer_tanque_cheio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tanque_comb',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
