# Generated by Django 5.2.6 on 2025-09-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_abastecer_litros_alter_veiculo_tanque_comb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='litros',
            field=models.DecimalField(decimal_places=2, help_text='Digie a quantidade de litros abasteecidos mostrado na bomba de combustível.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='tanque_cheio',
            field=models.BooleanField(default=False, help_text='Marque se o tanque foi cheio no abastecimento.'),
        ),
    ]
